---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-collector-secret
  namespace: checkmk-monitoring
data:
  # Secret must be a base64 encoded string. Use 'echo -n "STRING" | base64'
  cluster-collector-key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRRHQrci8xeFdXTTZiODIKTHlRRGhZaGNXR255akNya3E3SlBx
    d3prbnBLdXR2MzFwTUZPZzhwNnltdzFOQlYrUExrdDZHbVJGQmowSEFkRApiUmIyR2MrSW85aGZM
    WnhiVVFScTRsbVBRem0rNUVKSnVtZUpyMkFjaElBeGF4b1RVWlduWkdRMjFNbHVkTjlEClNEY1Vv
    aEdGY29zd2Q2ZWtja1RHSXVuaFpVdUF1NDFSQzBkRldFcVF3VkRuTUoyb1M3U2NxcDVGMGxSREZm
    VVQKZlQvbXFBTit2NGhCZjU3Y3BYVmdCditET0ZrQ2cwbGNxT1ZnUmRSVmtpZlhvL2hraHF4dkJw
    V3hSSllwWTJVRApQT0poL3F5ODNVWERiaGYxdnVLaFNwS2JZR2tWZFdtbi9MdDJmT3VrdW9Sa0M1
    SUYvWE5mOU1zWGdSTG90K3AzCktBSE1YM2UxQWdNQkFBRUNnZ0VCQUxvRVJXWDd2U3dQVGZveGtP
    bjd4NkcvTGxsN3ZNOXZjZnFhRG9McGZHaDYKK3ptMlphOVVqc0c2Vmlpa0pLUy9IRlJKRmJOa1RU
    a0thNWNGdjJ2d3N1cndmMkd1U2tpS3BIUlRwNE8zSFgwYgorTUNlcHUzVm1yL1B4bEJha2xCRmRr
    QVkxY2lTUFQxTXQzTmxFRURkaWVxUXBVSG1WYkRSN1BZZk5rZUxvUi9tCmVHYm1kb3RLNmZSSklj
    SnpVd2dtakkwYUIxQjZOYjNnSlluUm1SWXlKTlBjZE5acTR5ZDYxTmpBK0FQeWI1eGoKWlhvREpn
    d2c1NGNaQkphWS94cktiZ21YRGxoS3BsOXVwcnRUZ2ZBU3RiMkYwWnRaMWhPMGk2cWtXYzNtMGZy
    TQpUS0lYYVQzcmZ4RmVoOHBQOEs3QlB2R0NMNElsN0JMb0ZlNVV2Rjd4L0VVQ2dZRUErUFNtQnpF
    M2FuekdiemRzCkFQUjJuMVpia2pKcUd1TGwydlpEQlViekpVNEllMVdhcmcyUXBibWowdUhUeEdI
    NUZvbkNWZGJxVXU0R09ialcKN0xSL1FCZWNJZXRMN0tqQ05SS2ZLcE81MjRhdHc3Ti9Xbjg1Mm9k
    ZWQvK2QwMnJQZjkyQ0lIRFVZRGJSZjg1cgpaenJ0UVFnSHpHS0g0bm11dU5kU0JOUG9CdmNDZ1lF
    QTlMYVg5MklZVXRZbTlVZEIrVDNGanNyVXZBNHp4cE5xCm0rMEc5aVZmOTdPcUlQaTFlNXFZRTBW
    NExLYWVMV3JiclI0SEkySFg4UXVzSFdDWDVTbjdaVG1oamJLcW9vdTAKSkRZUmVjS3pvVFgzeUNP
    eDU3QWdURU91SDlncmpNU29jZHR6STBpWmNWTGk4TGlDTS9jRDlHSGlobituaENLcwo1ZmpnSjMv
    dTc3TUNnWUI0MVQyMFpmWHdzSWtidC9tcTZQeWVUNnI0WlpITVpPNk5mVk9BUHpTS21icFNLblYr
    CkgwVml1cHpDSVN2SXVJak9vS1I3UjJuS1FJOHkrdjBPUEhrNjRYcTlsOWZ0RU9mYUhLUzJaS2Nq
    M3RWK0ZDUXYKQjJ0TUhzSUNXa1gvTkd0c00xWVNhdEVadGVHdk44QTNoWWxjTkFxYzhBSG1NWXRW
    V2VVTVJOSHNkd0tCZ0FUcQo2bkRoT3NYblljOEtDSXhlcm1xcExzODhwZE8yd0t5emZiRlNuUFFZ
    V3pIZ2JaMDNSUmtXQzAweVovbFhyV1IwCk53YUIvOW5yTnlFOEFMRnRQNDBRTkd2cGpENUorbXZE
    M21RSkFwMFp2WW43RmFjblJlN2lhVXhnaHJlRWVESVoKaTkzSXByUzlTcXcxdVFBY1Zhc0NrSS9O
    WHV0cjJ2ZWdJYmtKZkI2N0FvR0JBUGVVbjY0cmprV05RdW9JVnBzVwpFeDNMS05MOW00TVlWLzg2
    eTg1UW1iYlZYdUhyZDI0bVRMMDN5RFk4MmxnV1Z0TjRuRUNOano2cFR5TzViK2dFCkg3alVGVmln
    MW1sSlFVSTQ5Q0ZkYzdIcjgxWEJmNElwUmJhSGVpUkFjS2VRbUl6VGZpU3pYRFRMVjUvR0NXSXAK
    QlhJcCt2YVN6eWh6WmRLK05FNnlYYVVwCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
  cluster-collector-keypass: Y2hlY2ttaw==
  cluster-collector-cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVFakNDQXZxZ0F3SUJBZ0lVUGdZRzlBd2JS
    WnN2cHBNVjFvajgvTHE4MjRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dhY3hDekFKQmdOVkJBWVRB
    a1JGTVE4d0RRWURWUVFJREFaQ1lYbGxjbTR4RVRBUEJnTlZCQWNNQ0UxMQpaVzVqYUdWdU1SVXdF
    d1lEVlFRS0RBeDBjbWxpWlRJNUlFZHRZa2d4Q3pBSkJnTlZCQXNNQWtsVU1TOHdMUVlKCktvWklo
    dmNOQVFrQkZpQjNaV0p0WVhOMFpYSkFZMjFyTGpFd0xqSXdNQzR6TGpJd0xtNXBjQzVwYnpFZk1C
    MEcKQTFVRUF3d1dZMjFyTGpFd0xqSXdNQzR6TGpJd0xtNXBjQzVwYnpBZUZ3MHlNVEE1TVRReE1U
    RTJNREJhRncweQpOREE1TVRNeE1URTJNREJhTUlHbk1Rc3dDUVlEVlFRR0V3SkVSVEVQTUEwR0Ex
    VUVDQXdHUW1GNVpYSnVNUkV3CkR3WURWUVFIREFoTmRXVnVZMmhsYmpFVk1CTUdBMVVFQ2d3TWRI
    SnBZbVV5T1NCSGJXSklNUXN3Q1FZRFZRUUwKREFKSlZERXZNQzBHQ1NxR1NJYjNEUUVKQVJZZ2Qy
    VmliV0Z6ZEdWeVFHTnRheTR4TUM0eU1EQXVNeTR5TUM1dQphWEF1YVc4eEh6QWRCZ05WQkFNTUZt
    TnRheTR4TUM0eU1EQXVNeTR5TUM1dWFYQXVhVzh3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0
    SUJEd0F3Z2dFS0FvSUJBUUR0K3IvMXhXV002YjgyTHlRRGhZaGNXR255akNya3E3SlAKcXd6a25w
    S3V0djMxcE1GT2c4cDZ5bXcxTkJWK1BMa3Q2R21SRkJqMEhBZERiUmIyR2MrSW85aGZMWnhiVVFS
    cQo0bG1QUXptKzVFSkp1bWVKcjJBY2hJQXhheG9UVVpXblpHUTIxTWx1ZE45RFNEY1VvaEdGY29z
    d2Q2ZWtja1RHCkl1bmhaVXVBdTQxUkMwZEZXRXFRd1ZEbk1KMm9TN1NjcXA1RjBsUkRGZlVUZlQv
    bXFBTit2NGhCZjU3Y3BYVmcKQnYrRE9Ga0NnMGxjcU9WZ1JkUlZraWZYby9oa2hxeHZCcFd4UkpZ
    cFkyVURQT0poL3F5ODNVWERiaGYxdnVLaApTcEtiWUdrVmRXbW4vTHQyZk91a3VvUmtDNUlGL1hO
    ZjlNc1hnUkxvdCtwM0tBSE1YM2UxQWdNQkFBR2pOREF5Ck1EQUdBMVVkRVFRcE1DZUNHQ291WTIx
    ckxqRXdMakl3TUM0ekxqSXdMbTVwY0M1cGI0SUxNVEF1TWpBd0xqTXUKTWpBd0RRWUpLb1pJaHZj
    TkFRRUxCUUFEZ2dFQkFKSG01S1ozc09va095bFR1cE95enlBZU9TbEJWV0t6MUp0RApnbmJGUmkr
    ZExFQzY2M2h1UE1BQTk1NjQwRGNFKzRkK2NLbVd2Q0lCNmdTanpHNVk5WGU4OHcwM3l5ZGIvWHNM
    CkdVYVVML20rNFA5Vnk2dm1DQ2I2c2xNRC9Kb0luSGtpNHZFaWswQ2dCaFExV1R0Um90UDZRMStH
    Y21RalhteDYKTXRNdjlWcU9DM0pNejFoV093dkZ6OVJ4Rk5CYjNNWmhGUWV1azJxUlBqV1hCSEdY
    cURIdDRWbndEbEFFaG5pRgpWaGVtYjJ3djNKY1ZIcXdaaEYrTTNNYnVMVTJUSE9ObXhaKzQ5T1I5
    ME9yMmhkQlZQQlRsM1FwaWYxWG9FSnhlClVQVmllUlZ5cnV6WTVzV3RQcTVRaGE2Vk5QbTQ3eEd3
    MXZVcU1vOGFyVmQ5bXpGWUFnND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
