---
apiVersion: v1
kind: Namespace
metadata:
  name: checkmk-integration
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: supervisor-token
#  namespace: checkmk-integration
#  annotations:
#    kubernetes.io/service-account.name: supervisor
#type: kubernetes.io/service-account-token
#data:
#    extra: YmFyCg==
#---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: supervisor
  namespace: checkmk-integration
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supervisor-reader
rules:
  - apiGroups:
      - ""  # core API group
      - apps
      - batch
      - autoscaling
      - authentication.k8s.io
    resources:
      - nodes
      - nodes/proxy
      - pods
      - deployments
      - replicasets
      - jobs
      - daemonsets
      - statefulsets
      - cronjobs
      - services
      - endpoints
      - ingresses
      - persistentvolumes
      - persistentvolumeclaims
      - storageclasses
      - horizontalpodautoscalers
      - replicasets
      - namespaces
      - resourcequotas
      - serviceaccounts
      - secrets
      - tokenreviews
    verbs:
      - "get"
      - "list"
      - "create"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: supervisor-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: supervisor-reader
subjects:
  - kind: ServiceAccount
    name: supervisor
    namespace: checkmk-integration

