---
- name: "Include authentication"
  ansible.builtin.import_playbook: auth.yml

# Ansible should wait for the control-plane pods to appear otherwise the kubectl secret command
# will fail in the next task
- name: "Wait for Kubernetes"
  hosts: "localhost"
  tasks:
    - name: "Wait for control-plane pods to appear"
      command: kubectl get pod --namespace=kube-system --selector tier=control-plane --output=jsonpath='{.items[*].metadata.name}'
      register: control_plane_pods
      until: item in control_plane_pods.stdout
      retries: 3
      delay: 20
      with_items:
          - etcd
          - kube-apiserver
          - kube-controller-manager
          - kube-scheduler

- name: "Provide registry credentials."
  hosts: "localhost"
  tasks:
    - name: "Docker login."
      command: docker login --username "{{ nexus_user }}" --password-stdin "{{ container_image_registry_url }}"
      args:
        stdin: "{{ nexus_password }}"
        creates: /home/jenkins/.docker/config.json
      when: (container_image_registry_url != "docker.io")
    - name: "Clean up a potentially existing secret"
      command: "kubectl delete secret registry-auth --ignore-not-found=true"
    - name: "Create image pull secret from Docker config."
      command: kubectl create secret generic registry-auth --from-file=.dockerconfigjson=/home/jenkins/.docker/config.json --type=kubernetes.io/dockerconfigjson
      when: (container_image_registry_url != "docker.io")


- name: "Create Kubernetes ServiceAccount for integration tests token"
  hosts: "localhost"
  tasks:
    - name: "Deploy YAML file to Kubernetes cluster"
      command: "kubectl apply -f ../../deploy/integration-sa.yaml"
    - name: "Verify service account is created"
      command: "kubectl get serviceaccount supervisor -n checkmk-integration --ignore-not-found"
      register: serviceaccount
      until: serviceaccount.stdout | length > 0
#    - name: "Create API token secret"
#      command: "kubectl create token --duration=0s -n checkmk-integration supervisor"
    - name: "Apply secret to serviceaccount"
      shell: |
          kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: supervisor-token
            namespace: checkmk-integration
            annotations:
              kubernetes.io/service-account.name: supervisor
          type: kubernetes.io/service-account-token
          EOF

