---
collections:
- name: community.general
  version: 4.8.0
- name: ansible.posix
  version: 1.4.0
- name: kubernetes.core
  version: 2.2.2

roles:
- src: geerlingguy.docker
  version: 4.1.1
- src: geerlingguy.kubernetes
  version: 7.1.1
- src: geerlingguy.containerd
  version: 1.2.0
