# Default values for checkmk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

tlsCommunication:
  enabled: false # TODO: true
  # ## Secret name containing the TLS certificate for checkmk with the fields: cluster-collector-key, cluster-collector-cert, checkmk-ca-cert
  # ## Secret must be manually created in the namespace. If left 
  # tlsSecretName: ""
  clusterCollectorKey: "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSURFVU10MGErY3hpVCtXWkNGc2p0QzlDcXVNVExLd0h1YjA1aFRjQnNQNkRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFYUFPNlhQT3hCMStqNTA0YlN0UXEvRlkzZjd6bmIxV1FUNlpoSzg1NFFlKyt4L083NHRPVApDbCtRWXdJK1dDYUVnMCtmMG5zczlrVjNMMmdCZDFKODFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo="
  clusterCollectorCert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJRENDQXNhZ0F3SUJBZ0lVY0Z2cVN2Z2k5MFFOdGRLNUx4U0R1MVF1Z2Nrd0NnWUlLb1pJemowRUF3SXcKWWpFTE1Ba0dBMVVFQmhNQ1JFVXhFREFPQmdOVkJBZ01CMEpoZG1GeWFXRXhEekFOQmdOVkJBY01CazExYm1sagphREVNTUFvR0ExVUVDZ3dEZERJNU1Rd3dDZ1lEVlFRTERBTmtaWFl4RkRBU0JnTlZCQU1NQzJOb1pXTnJiV3N1ClkyOXRNQjRYRFRJeU1ESXhNVEUwTlRRMU5sb1hEVEkwTVRFd056RTBOVFExTmxvd2dZa3hDekFKQmdOVkJBWVQKQWtSRk1SQXdEZ1lEVlFRSURBZENZWFpoY21saE1ROHdEUVlEVlFRSERBWk5kVzVwWTJneEREQUtCZ05WQkFvTQpBM1F5T1RFTU1Bb0dBMVVFQ3d3RFpHVjJNVHN3T1FZRFZRUUREREpqYkhWemRHVnlMV052Ykd4bFkzUnZjaTVqCmFHVmphMjFyTFcxdmJtbDBiM0pwYm1jdVkyeDFjM1JsY2k1c2IyTmhiREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcKU000OUF3RUhBMElBQkdnRHVsenpzUWRmbytkT0cwclVLdnhXTjMrODUyOVZrRSttWVN2T2VFSHZ2c2Z6dStMVAprd3Bma0dNQ1BsZ21oSU5QbjlKN0xQWkZkeTlvQVhkU2ZOU2pnZ0V3TUlJQkxEQWRCZ05WSFE0RUZnUVVZVEZDCjhxR1liNnR6MFZac0R0QzVpVnRzRDVrd2daOEdBMVVkSXdTQmx6Q0JsSUFVVVVlN2Iyb2NaRXhBMkxoUlpCZzMKaUQyZTJvR2hacVJrTUdJeEN6QUpCZ05WQkFZVEFrUkZNUkF3RGdZRFZRUUlEQWRDWVhaaGNtbGhNUTh3RFFZRApWUVFIREFaTmRXNXBZMmd4RERBS0JnTlZCQW9NQTNReU9URU1NQW9HQTFVRUN3d0RaR1YyTVJRd0VnWURWUVFECkRBdGphR1ZqYTIxckxtTnZiWUlVTytDSUdDcFhmNGQ1KzJGRnlKRVVERkR5VDk4d0RBWURWUjBUQkFVd0F3RUIKL3pBTEJnTlZIUThFQkFNQ0F2d3dRd1lEVlIwUkJEd3dPb0l5WTJ4MWMzUmxjaTFqYjJ4c1pXTjBiM0l1WTJobApZMnR0YXkxdGIyNXBkRzl5YVc1bkxtTnNkWE4wWlhJdWJHOWpZV3lIQkFwc0VoRXdDUVlEVlIwU0JBSXdBREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTk4VEFPWVRQMG9GY2x2R2dheTVick9Samhxa2IvL3dydXEvd0ZEaFgKZ2pVQ0lHL25rY05BcUhFY3RRSHNkRmxYZ1d1cU4wdjRlSUpUMC9DeGxNSG9ZVnQ2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  checkmkCaCert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNHVENDQWIrZ0F3SUJBZ0lVTytDSUdDcFhmNGQ1KzJGRnlKRVVERkR5VDk4d0NnWUlLb1pJemowRUF3SXcKWWpFTE1Ba0dBMVVFQmhNQ1JFVXhFREFPQmdOVkJBZ01CMEpoZG1GeWFXRXhEekFOQmdOVkJBY01CazExYm1sagphREVNTUFvR0ExVUVDZ3dEZERJNU1Rd3dDZ1lEVlFRTERBTmtaWFl4RkRBU0JnTlZCQU1NQzJOb1pXTnJiV3N1ClkyOXRNQjRYRFRJeU1ESXhNVEUwTlRNMU0xb1hEVEl5TURNeE16RTBOVE0xTTFvd1lqRUxNQWtHQTFVRUJoTUMKUkVVeEVEQU9CZ05WQkFnTUIwSmhkbUZ5YVdFeER6QU5CZ05WQkFjTUJrMTFibWxqYURFTU1Bb0dBMVVFQ2d3RApkREk1TVF3d0NnWURWUVFMREFOa1pYWXhGREFTQmdOVkJBTU1DMk5vWldOcmJXc3VZMjl0TUZrd0V3WUhLb1pJCnpqMENBUVlJS29aSXpqMERBUWNEUWdBRTBtZW4vQ3RpUUJyUGpnZzVtcDF1NnRxQXg2c1NFeWxCRHUyeXNMMHgKTEY1Z1J5SFFjYndodVZ6eUp0K3NjTDErTm1lc1NTd3E5WFBtQVR1RVYwTTJhNk5UTUZFd0hRWURWUjBPQkJZRQpGRkZIdTI5cUhHUk1RTmk0VVdRWU40ZzludHFCTUI4R0ExVWRJd1FZTUJhQUZGRkh1MjlxSEdSTVFOaTRVV1FZCk40ZzludHFCTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUx4RzVhSDEKemJjMGd0MDdYTHlId2NUbDJMMW1RNnJ5YlQ1NXdlRk5keU9JQWlCK0lldVltdUJyYkVPQ2RvbktiN3ZFOWFTNgpvRXo3WHNiaWpnMldVWGxDSUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

imagePullSecrets: []

## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  enabled: false
  # specify ipBlock cidrs here for your ingress to the cluster-collector, especially the checkmk server ip range
  allowIngressFromCIDRs: []
  # - 127.0.0.1/32 # e.g. Checkmk Server
  # - 127.0.0.1/24 # e.g. Metallb speakers

## Configuration for cluster-collector
clusterCollector:
  image:
    repository: checkmk/kubernetes-collector
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "main_2022.02.16" # main_<YYYY.MM.DD>

  podAnnotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    privileged: false
    readOnlyRootFilesystem: true
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  rbac:
    pspEnabled: true

  service:
    # if required specify "NodePort" here to expose the cluster-collector via the "nodePort" specified below
    type: ClusterIP
    port: 8080
    # nodePort: 30035

  ingress:
    enabled: false
    className: ""
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: checkmk-cluster-collector.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    limits:
      cpu: 300m
      memory: 2000Mi
    requests:
      cpu: 150m
      memory: 200Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

## Configuration for node-collector
nodeCollector:
  podAnnotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default

  podSecurityContext: {}
    # fsGroup: 2000

  rbac:
    pspEnabled: true

  machineSectionsCollector:
    image:
      repository: checkmk/kubernetes-collector
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "main_2022.02.16" # main_<YYYY.MM.DD>

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001

    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 200Mi

  containerMetricsCollector:
    image:
      repository: checkmk/kubernetes-collector
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "main_2022.02.16" # main_<YYYY.MM.DD>

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001

    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 200Mi

  cadvisor:
    image:
      repository: checkmk/cadvisor-patched
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "main_2022.02.16" # main_<YYYY.MM.DD>

    additionalArgs:
      - "--housekeeping_interval=30s"
      - "--max_housekeeping_interval=35s"
      - "--event_storage_event_limit=default=0"
      - "--event_storage_age_limit=default=0"
      - "--store_container_labels=false"
      - "--whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid"
      - "--global_housekeeping_interval=30s"
      - "--event_storage_event_limit=default=0"
      - "--event_storage_age_limit=default=0"
      - "--disable_metrics=percpu,process,sched,tcp,udp,diskIO,disk,network"
      - "--allow_dynamic_housekeeping=true"
      - "--storage_duration=1m0s"

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add: ["CAP_SYS_PTRACE"]
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001

    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 150m
        memory: 200Mi
