---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk.fullname" . }}-cadvisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-cadvisor
spec:
  type: ClusterIP
  ports:
    - name: cadvisor
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "checkmk.selectorLabels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-cadvisor
