{{- if .Values.networkPolicy.enabled }}
---
# Deny all incoming/outgoing traffic to/from cadvisor
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "checkmk.fullname" . }}-cadvisor-deny-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      component: {{ include "checkmk.fullname" . }}-cadvisor
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
---
# Allow incoming traffic from node-collector to cadvisor
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "checkmk.fullname" . }}-cadvisor-allow-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      component: {{ include "checkmk.fullname" . }}-cadvisor
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
        podSelector:
          matchLabels:
            component: {{ include "checkmk.fullname" . }}-node-collector
      ports:
      - port: 8080
{{- end }}