---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "checkmk.fullname" . }}-cadvisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-cadvisor