{{- if .Values.tlsCommunication.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "checkmk.fullname" . }}-checkmk-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
data:
  cluster-collector-key: {{ required "With TLS enabled you need to provide a clusterCollectorKey." .Values.tlsCommunication.clusterCollectorKey | b64enc | quote }}
  cluster-collector-cert: {{ required "With TLS enabled you need to provide a clusterCollectorCert." .Values.tlsCommunication.clusterCollectorCert | b64enc | quote }}
  checkmk-ca-cert: {{ required "With TLS enabled you need to provide a checkmkCaCert." .Values.tlsCommunication.checkmkCaCert | b64enc | quote }}
{{- end }}