---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkmk.fullname" . }}-cluster-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-cluster-collector
  {{- with .Values.clusterCollector.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.clusterCollector.service.type }}
  ports:
    - name: api
      port: {{ .Values.clusterCollector.service.port }}
      targetPort: api
      {{- if eq .Values.clusterCollector.service.type "NodePort" }}
      nodePort: {{ required "You need to specify a nodePort if using the service type NodePort." .Values.clusterCollector.service.nodePort }}
      {{- end }}
      protocol: TCP
  selector:
    {{- include "checkmk.selectorLabels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-cluster-collector
