{{- if .Values.rbac.pspEnabled }}
{{- if ge (int .Capabilities.KubeVersion.Minor) 25 }}
{{- fail "PodSecurityPolicies (PSPs) were deprecated in Kubernetes v1.21, and removed from Kubernetes in v1.25. Please make sure to disable PSPs." }}
{{- end }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "checkmk.fullname" . }}-cluster-collector
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
{{- if .Values.rbac.pspAnnotations }}
  annotations:
    {{ toYaml .Values.rbac.pspAnnotations | nindent 4 }}
{{- end }}
spec:
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  defaultAllowPrivilegeEscalation: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities: [ALL]
  allowedCapabilities: []
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  hostPorts:
    - min: 0
      max: 65535
  allowedHostPaths:
    - pathPrefix: "/var/run"
      readOnly: true
    - pathPrefix: "/sys"
      readOnly: true
    - pathPrefix: "/var/lib/docker"
      readOnly: true
  volumes:
    - secret
    - hostPath
    - emptyDir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "checkmk.fullname" . }}-cluster-collector
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "checkmk.fullname" . }}-cluster-collector
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "checkmk.fullname" . }}-cluster-collector
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: cluster-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "checkmk.fullname" . }}-cluster-collector
subjects:
  - kind: ServiceAccount
    name: {{ template "checkmk.serviceAccountName.clusterCollector" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}