{{- /* Deploy only if .Values.gkeAutopilot.allowlistPaths is non-empty */ -}}
{{- if and .Values.gkeAutopilot (hasKey .Values.gkeAutopilot "allowlistPaths") }}
apiVersion: auto.gke.io/v1
kind: AllowlistSynchronizer
metadata:
  name: {{ include "checkmk.fullname" . }}-allowlist-synchronizer
spec:
  allowlistPaths:
{{- range .Values.gkeAutopilot.allowlistPaths }}
    - "{{ . }}"
{{- end }}
{{- end }}
