---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector-container-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    component: {{ include "checkmk.fullname" . }}-node-collector
    app: {{ include "checkmk.fullname" . }}-node-collector-container-metrics