{{- if .Values.rbac.pspEnabled }}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector-machine-sections
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
{{- if .Values.rbac.pspAnnotations }}
  annotations:
    {{ toYaml .Values.rbac.pspAnnotations | nindent 4 }}
{{- end }}
spec:
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  defaultAllowPrivilegeEscalation: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities: [ALL]
  allowedCapabilities: []
  privileged: false
  hostIPC: false
  hostPID: false
  hostNetwork: false
  hostPorts:
    - min: 0
      max: 65535
  volumes:
    - secret
    - emptyDir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector-machine-sections
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resourceNames:
      - {{ include "checkmk.fullname" . }}-node-collector-machine-sections
    resources:
      - podsecuritypolicies
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector-machine-sections
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-node-collector-machine-sections
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "checkmk.fullname" . }}-node-collector-machine-sections
subjects:
  - kind: ServiceAccount
    name: {{ template "checkmk.serviceAccountName.nodeCollector.machineSectionsCollector" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}