---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector-container-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-node-collector-container-metrics
    component: {{ include "checkmk.fullname" . }}-node-collector
spec:
  selector:
    matchLabels:
      {{- include "checkmk.selectorLabels" . | nindent 6 }}
      app: {{ include "checkmk.fullname" . }}-node-collector-container-metrics
      component: {{ include "checkmk.fullname" . }}-node-collector
  template:
    metadata:
      annotations:
        {{- if .Values.tlsCommunication.enabled }}
        checksum/config: {{ include (print $.Template.BasePath "/checkmk-secret.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.nodeCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "checkmk.selectorLabels" . | nindent 8 }}
        app: {{ include "checkmk.fullname" . }}-node-collector-container-metrics
        component: {{ include "checkmk.fullname" . }}-node-collector
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "checkmk.fullname" . }}-node-collector
      securityContext:
        {{- toYaml .Values.nodeCollector.podSecurityContext | nindent 8 }}
      containers:
        - name: container-metrics-collector
          securityContext:
            {{- toYaml .Values.nodeCollector.containerMetricsCollector.securityContext | nindent 12 }}
          image: "{{ .Values.nodeCollector.containerMetricsCollector.image.repository }}:{{ .Values.nodeCollector.containerMetricsCollector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nodeCollector.containerMetricsCollector.image.pullPolicy }}
          command:
            - "/usr/local/bin/checkmk-container-metrics-collector"
          args:
            - "--log-level={{ .Values.nodeCollector.logLevel }}"
          {{- if .Values.tlsCommunication.enabled }}
            - "--secure-protocol"
            #- "--verify-ssl" # TODO enable again
          {{- end }}
          {{- if .Values.tlsCommunication.enabled }}
          volumeMounts:
            - name: checkmk-ca-cert
              mountPath: /etc/ca-certificates/checkmk-ca-cert.pam
              subPath: checkmk-ca-cert.pam
              readOnly: true
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_COLLECTOR_SERVICE_HOST
              value: "{{ include "checkmk.fullname" . }}-cluster-collector.{{ .Release.Namespace }}"
            - name: CLUSTER_COLLECTOR_SERVICE_PORT_API
              value: "{{ .Values.clusterCollector.service.port }}"
            - name: CADVISOR_SERVICE_HOST
              value: "{{ include "checkmk.fullname" . }}-cadvisor.{{ .Release.Namespace }}"
            - name: CADVISOR_SERVICE_PORT
              value: "8080"
          resources:
            {{- toYaml .Values.nodeCollector.containerMetricsCollector.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
      {{- if .Values.tlsCommunication.enabled }}
      volumes:
        - name: checkmk-ca-cert
          secret:
            secretName: {{ include "checkmk.fullname" . }}-checkmk-tls
            items:
              - key: checkmk-ca-cert
                path: checkmk-ca-cert.pam
      {{- end }}