---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "checkmk.fullname" . }}-node-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
    app: {{ include "checkmk.fullname" . }}-node-collector
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  selector:
    matchLabels:
      {{- include "checkmk.selectorLabels" . | nindent 6 }}
      app: {{ include "checkmk.fullname" . }}-node-collector
  template:
    metadata:
      {{- with .Values.nodeCollector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "checkmk.selectorLabels" . | nindent 8 }}
        app: {{ include "checkmk.fullname" . }}-node-collector
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "checkmk.fullname" . }}-node-collector
      securityContext:
        {{- toYaml .Values.nodeCollector.podSecurityContext | nindent 8 }}
      containers:
        - name: machine-sections-collector
          securityContext:
            {{- toYaml .Values.nodeCollector.machineSectionsCollector.securityContext | nindent 12 }}
          image: "{{ .Values.nodeCollector.machineSectionsCollector.image.repository }}:{{ .Values.nodeCollector.machineSectionsCollector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nodeCollector.machineSectionsCollector.image.pullPolicy }}
          command:
            - "/usr/local/bin/checkmk-machine-sections-collector"
          {{- if .Values.tlsCommunication.enabled }}
          args:
            - "--secure-protocol"
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CLUSTER_COLLECTOR_SERVICE_HOST
              value: "{{ include "checkmk.fullname" . }}-cluster-collector.{{ .Release.Namespace }}"
            - name: CLUSTER_COLLECTOR_SERVICE_PORT_API
              value: "{{ .Values.clusterCollector.service.port }}"
          resources:
            {{- toYaml .Values.nodeCollector.machineSectionsCollector.resources | nindent 12 }}
        - name: container-metrics-collector
          securityContext:
            {{- toYaml .Values.nodeCollector.containerMetricsCollector.securityContext | nindent 12 }}
          image: "{{ .Values.nodeCollector.containerMetricsCollector.image.repository }}:{{ .Values.nodeCollector.containerMetricsCollector.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nodeCollector.containerMetricsCollector.image.pullPolicy }}
          command:
            - "/usr/local/bin/checkmk-container-metrics-collector"
          {{- if .Values.tlsCommunication.enabled }}
          args:
            - "--secure-protocol"
          {{- end }}
          env:
            - name: CLUSTER_COLLECTOR_SERVICE_HOST
              value: "{{ include "checkmk.fullname" . }}-cluster-collector.{{ .Release.Namespace }}"
            - name: CLUSTER_COLLECTOR_SERVICE_PORT_API
              value: "{{ .Values.clusterCollector.service.port }}"
          resources:
            {{- toYaml .Values.nodeCollector.containerMetricsCollector.resources | nindent 12 }}
        - name: cadvisor
          securityContext:
            {{- toYaml .Values.nodeCollector.cadvisor.securityContext | nindent 12 }}
          image: "{{ .Values.nodeCollector.cadvisor.image.repository }}:{{ .Values.nodeCollector.cadvisor.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nodeCollector.cadvisor.image.pullPolicy }}
          command:
            - "/usr/bin/cadvisor"
          args:
            - "--housekeeping_interval=30s"
            - "--max_housekeeping_interval=35s"
            - "--event_storage_event_limit=default=0"
            - "--event_storage_age_limit=default=0"
            - "--store_container_labels=false"
            - "--whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid"
            - "--global_housekeeping_interval=30s"
            - "--event_storage_event_limit=default=0"
            - "--event_storage_age_limit=default=0"
            - "--disable_metrics=percpu,process,sched,tcp,udp,diskIO,disk,network"
            - "--allow_dynamic_housekeeping=true"
            - "--storage_duration=1m0s"
          resources:
            {{- toYaml .Values.nodeCollector.cadvisor.resources | nindent 12 }}
          volumeMounts:
            # - name: var-run
            #   mountPath: /var/run
            #   readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
      #automountServiceAccountToken: false # TODO required (?) for cadvisor, but required the other way round for checkmk collectors?
      terminationGracePeriodSeconds: 30
      volumes:
        # - name: var-run
        #   hostPath:
        #     path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker