---
- name: "Destroy."
  hosts: "{{ run_hosts }}"
  gather_facts: 'false'
  tasks:
    - name: "Destroy VMs."
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password }}"
        api_host: pve-fra-001.tribe29.com
        state: absent
        node: pve-fra-001
        vmid: "{{ pve_id }}"
        force: 'yes'
      delegate_to: localhost
